### ISSUE TITLE
Some functions not found

### ISSUE THREAD

**Issue by pssguy** [mountainMath/cansim#11]
```
> get_cansim_table_info("39-10-0049")

Error in get_cansim_table_info("39-10-0049") : 
  could not find function "get_cansim_table_info"
```

get_cansim_column_list(), for example, gives similar error. 

However, get_cansim_table_overview() works fine

get_cansim(), get_cansim_changed_tables()  and get_cansim_cube_metadata() are the others that appear
to be available

I have restarted the R session and reinstalled the package

**Comment by mountainMath** [comment]
Some of these are only internal functions at this point and not exported. They have not been tested well and might change significantly. You can access them using three colons, like
```
cansim:::get_cansim_table_info("39-10-0049")
```
But the syntax and what's returned might change quite a bit in future versions.

**Comment by pssguy** [comment]
Thanks for that. I'm not familiar enough with packages and assumed documentation would only show
automatically available functions
 Anyways, it's already proving very useful. I'll keep on idea on developments/amendments
