### ISSUE TITLE
Can I download only subset of the data?

### ISSUE THREAD

**Issue by biswask** [mountainMath/cansim#12]
Hello,
I have a quick question. Is there any way to download only a subset of the data (for example, for CANSIM table# 282-0001, I want to download data only for the last 2 years)?

Thanks in advance,
Keya.

**Comment by mountainMath** [comment]
There are two ways you can do this. One is to simply download the whole table and then filter, e.g.
```
get_cansim("282-0001") %>% filter(REF_DATE>="2016")
```
to filter down to data starting from 2016.

Now there is also a new function that allows targeted download of a select cansim vectors for a specific time period, so you can use
```
get_cansim_vector("v2091030",as.Date("2016-01-01"))
```
to get all data for cansim vector "v2091030" released 2016 or later. This works if you want data for a specific vector (or list of vectors).

**Comment by mountainMath** [comment]
I just added functionality for two more ways to get this kind of data. To get data for a specific (list of) vector(s) for the past 10 time periods you can use
```
get_cansim_vector_for_latest_periods("v2091030",10)
```
or to get the last 10 periods by table and coordinate you can use
```
get_cansim_data_for_table_coord_periods("282-0001","1.1.1.1.0.0.0.0.0.0",10)
```
For these methods you will need to either know the specific vector number or coordinate that you are interested in.

**Comment by biswask** [comment]
Hi,
Thank you so much for your quick response. I tried to run both of the codes: 
      get_cansim_vector_for_latest_periods("v2091030",10)  &  
      get_cansim_data_for_table_coord_periods("282-0001","1.1.1.1.0.0.0.0.0.0",10)

But I am getting error massages of  " could not find function "get_cansim_vector_for_latest_periods" and "could not find function "get_cansim_vector_for_latest_periods" .  Can you please advise?

thanks again,
Keya

**Comment by pssguy** [comment]
Make sure you have the latest development version and run function as
cansim:::get_cansim_vector_for_latest_periods("v2091030",10)

That should work 
Andrew ClarkIndependent Consultant/Contractor Interactive Web AppsNorth Vancouver(1) 778 917 9649 (cell)(1) 604 770 0709 (home)http://mytinyshinys.com
 



|  | Virus-free. www.avast.com



  |

    On Thursday, July 5, 2018 5:36 PM, biswask <notifications@github.com> wrote:
 

 Hi,
Thank you so much for your quick response. I tried to run both of the codes:
get_cansim_vector_for_latest_periods("v2091030",10) &
get_cansim_data_for_table_coord_periods("282-0001","1.1.1.1.0.0.0.0.0.0",10)But I am getting error massages of " could not find function "get_cansim_vector_for_latest_periods" and "could not find function "get_cansim_vector_for_latest_periods" . Can you please advise?thanks again,
Keya—

**Comment by biswask** [comment]
Hello,

Yes it did work :).
I have one more question. So when I use the
"get_cansim_vector_for_latest_periods" or
"get_cansim_data_for_table_coord_periods" functions, the data I am getting
does not contain all the columns. Is there any way to getting all the
columns as well? For example, I have attached a csv file containing last
month's (May) data only. Is there any way to download only the last month
data  from the website in the same way as shown in the attached csv file. I
have some time constrain, that's why I don't want to download the whole
data file, rather a subset of it.
I know I am asking a lot. Sorry for that.

Thanks again,
Keya.

**Comment by mountainMath** [comment]
Email attachments don't work for GitHub. If you also want data for different vectors you can pass a list of vectors to the function instead of just a single one. If you are looking for more columns like e.g. units of measurement and such, the added API functions don't provide that all of that data. The scale factor is present though, and you can pass the results to the `normalize_cansim_values` function to automatically rescale them. It won't be able to automatically rescale percentages though.

**Comment by biswask** [comment]
Hi,
Thanks for your response.  I have another question. While I tried the this code:
  get_cansim("282-0001") %>% filter(REF_DATE>="2016")
I got an error massage saying "Error in filter(., REF_DATE >= "2016") : object 'REF_DATE' not found". 
I checked the column name which seems correct to me. But still getting this error massage for 4/5 data sets I have tried so far. Can you please advise?
Thanks again!

**Comment by mountainMath** [comment]
Make sure you are using the dplyr version of filter. Either load dplyr library or use 
```
get_cansim("282-0001") %>% dplyr::filter(REF_DATE>="2016")
```

**Comment by biswask** [comment]
It's working Thank you so much once again!
