### ISSUE TITLE
cache_path option should have a more descriptive name

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cansim#15]
Currently the reference in options for the cansim package cache is just called `cache_path`. This should be more descriptive, especially when used in profiles that have a number of other similar named options. For example, the cancensus package uses `cancensus.cache_path` as the option name. I would suggest adjusting the cache option name here to something like `cansim.cache_path`.

**Comment by mountainMath** [comment]
Should have paid attention to this before. Might be a minor inconvenience to rename this now. But not too bad. It's only for the updated cansim table list.

Two options. Just change it now, or change it but fall back to cache_path in case the `cansim.cache_path` is not set and `cache_path` is.

**Comment by mountainMath** [comment]
Went with the first option, changed to `cansim.cache_path`. User is prompted to set that if not set and user requests a refresh.
