### ISSUE TITLE
get_cansim_column_list

### ISSUE THREAD

**Issue by jciconsult** [mountainMath/cansim#16]
Has this function been implemented?

**Comment by mountainMath** [comment]
Yes, but it's still only an internal function and might change in the future. You can access it already with the triple-column notation, but be aware that it is still in beta and the return result may change.

Example:

```
cansim:::get_cansim_column_list("33-10-0001")
```

**Comment by jciconsult** [comment]
For table 36-10-0402, it returns
[1] "Geography"                                            
[2] "Value"                                                
[3] "North American Industry Classification System (NAICS)"
The trouble is the column name is GEO in the retrieved table.
What I am trying to do is identify in a general fashion, the column names of the dimensions of the cube.
