### ISSUE TITLE
Suggestion - XTS

### ISSUE THREAD

**Issue by jciconsult** [mountainMath/cansim#30]
A lot of us would want to use time series objects rather than tibbles.  I have been playing with tbl2xts.  It requires the date as a date type rather than character.  You might consider an option in the vector routine to either return xts as Quandl does or at least to convert the REF_DATE to a standard date.

**Comment by mountainMath** [comment]
Which table are you looking at? The `normalize_cansim_values` function attempts to parse the REF_DATE and store the resulting Date object in a column called "Date" if successful.

**Comment by mountainMath** [comment]
Not sure. I would tend to agree. Casting the data into a time series object is pretty straight forward, not sure we want to add a function to do this. It could be done out of the box for the "vector" functions, but would require manual work to first filter things down when dealing with whole tables. I could write a vignette that shows how to do that. 

Another option is to look into the `tibbletime` package, but I have no experience with that.

**Comment by dshkol** [comment]
I think converting to xts is outside the scope of this package and can be done as required through a variety of means outside the package. 

Using additional packages in vignettes adds dependencies to the package for installation. It may be better to work that in via a post or somewhere else.
