### ISSUE TITLE
include details of StatsCan open data licence in README & documentation?

### ISSUE THREAD

**Issue by stephhazlitt** [mountainMath/cansim#32]
This is a super useful package @dshkol & @mountainMath, many thanks 🙏

Wondering if it would be useful to include some documentation on the licence details for sourcing and using CANSIM tables pulled from the Statistics Canada website? Almost all data products are released under the [Statistics Canada Open Licence Agreement](https://www.statcan.gc.ca/eng/reference/licence), except for a [few exceptions that have there own licence agreement](https://www.statcan.gc.ca/eng/reference/exceptions).

**Comment by mountainMath** [comment]
That's a good point, we should include that. I now wonder if the metadata has license information. Will investigate and include in the next update.

**Comment by dshkol** [comment]
@mountainMath any update on the license info?

**Comment by mountainMath** [comment]
The cansim tables are all covered by the standard [Statistics Canada Open Licence Agreement](https://www.statcan.gc.ca/eng/reference/licence). At least that's my reading of [point 3 in the FAQ](https://www.statcan.gc.ca/eng/reference/licence-faq#a3) that explicitly states that only postal code and PUMF data come with different licence agreements.

**Comment by dshkol** [comment]
Does that require a different type of license for the code or does the standard MIT apply?

**Comment by stephhazlitt** [comment]
The code licence is independent of a data licence, as far as I understand. If you house data in a repo, you place a copy of the data licence in the folder with the raw data. See [here for an example](https://github.com/bcgov/bcmaps.rdata). In the case of `cansim`&mdash;which goes and gets data for you&mdash;I just thought that adding the data licence details to the documentation would be useful for the user.

**Comment by dshkol** [comment]
@stephhazlitt, do you think that the changes in #38 sufficient to meet requirements here?

**Comment by stephhazlitt** [comment]
Yep, looks great.

**Comment by mountainMath** [comment]
Addressed in https://github.com/mountainMath/cansim/pull/38
