### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by PrahladaVaradan** [mountainMath/cansim#51]
While trying to access data through this package behind firewall, I got the following curl error:

GDP_Data <- get_cansim("36-10-0104-01")
Accessing CANSIM NDM product 36-10-0104
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached: Connection timed out after 10015 milliseconds

This can be resolved with the following code:

library(httr)
  set_config(use_proxy(url="http-proxy", port=##, username="###",password="####"))

**Comment by mountainMath** [comment]
Thanks, that's a great tip. Will work that into the documentation.
