### ISSUE TITLE
Using French language option does not fold metadata

### ISSUE THREAD

**Issue by ghawkins-ott** [mountainMath/cansim#53]
I'm using the 0.2.0 package to load some LFS data (specifically 1410028701) and when I add the <language="fr"> option at the end it does not append the metadata to the table.  When using "en" it works but not with french.

Example:
> x2820087fr <- get_cansim(1410028701,language="fr",refresh=TRUE)
Accessing CANSIM NDM product 14-10-0287
Using ',' as decimal and '.' as grouping mark. Use read_delim() for more control.
|=================================================================================================| 100%  928 MB

> x2820087en <- get_cansim(1410028701,language="en",refresh=TRUE)
Accessing CANSIM NDM product 14-10-0287
Parsing data
|=================================================================================================| 100%  918 MB
Folding in metadata

The resulting "fr" table doesn't include the meta-data columns whereas the english one does.

**Comment by mountainMath** [comment]
Merged into master, together with some pkgdown changes. https://github.com/mountainMath/cansim/pull/55

**Comment by ghawkins-ott** [comment]
Thanks! :)
