### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by PrahladaVaradan** [mountainMath/cansim#56]
Team, 

Tried downloading the zip file to install but didn't work. Installing through the code shared here (via remotes) din't work either.

Tried the following method and I get the following error:

install.packages("https://github.com/mountainMath/cansim.git", repos = NULL, type = "source")

install.packages("C:/Users/kx3/Downloads/cansim-master.zip", repos = NULL, type = "source")

Error in getOctD(x, offset, len) : invalid octal digit
In R CMD INSTALL
Warning message:
In install.packages("https://github.com/mountainMath/cansim.git",  :
  installation of package ‘C:/Users/xxx/AppData/Local/Temp/RtmpqMyxEI/downloaded_packages/cansim.git’ had non-zero exit status

**Comment by mountainMath** [comment]
You should use
```
# install.packages("remotes")
remotes::install_github("mountainmath/cansim")
```
as described in the [README](https://github.com/mountainMath/cansim) or the [documentation](https://mountainmath.github.io/cansim/index.html).
