### ISSUE TITLE
Changed NDM API and GeoUIDs

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cansim#60]
StatCan made some changes to their API. The GeoUID now comes down as a vector instead of a string. So e.g. '["933"]' instead of "933" for Vancouver CMA. (Same thing e.g. for NAICS categories.) Maybe there are cases where they send down more than one. That makes it a pain to link to geographies from `cancensus`. 

Thinking we should parse out the offending with `mutate(GeoUID = gsub("\\[|\\]", "", GeoUID)`, maybe in the `normalize_cansim_values` helper. The disadvantage is that there is probably a reason for this change, and that reason is that there probably are cases where there is more than one GeoUID getting sent down. In that case, the GeoUIDs will still be comma-separated after parsing out the brackets.

**Comment by mountainMath** [comment]
Thinking now that this should be part of the base `get_cansim` functionality, not the `normalize_cansim_values`. This change comes from StatCan changes how it codes classification codes, possibly to allow for a list rather than a single value. I suggest we strip the brackets for GeoUIDs by default, guessing there are no cases where there are several GeoUIDs for a region and this functionality is only needed for classification codes for other columns.

**Comment by dshkol** [comment]
Fixed in #64
