### ISSUE TITLE
Can't download "Table: 14-10-0328-01"

### ISSUE THREAD

**Issue by biswask** [mountainMath/cansim#61]
Hello,
I am trying to download a data (Table: 14-10-0328-01) form Statistics Canada website from this morning and getting the following error massage:
"Got timeout from StatCan, trying again"
Here is the code I have used: 
jvws_2850004=get_cansim("285-0004",refresh = TRUE)

Can you please help me solving this problem?

Thanks in advance, 
Keya.

**Comment by mountainMath** [comment]
That table is quite large and it seems like the connection to StatCan is quite slow today, so it won't download within the 200 seconds after which `cansim` cuts the connection. As a workaround I pushed changes to the master branch that expose the internal timeout parameter. If you install the current version from GitHub it should work by manually choosing a large timeout.
```
jvws_2850004=get_cansim("285-0004", refresh = TRUE, timeout=1000)
```
worked for me.

**Comment by biswask** [comment]
Thanks for the suggestion. But it didn't work for me. Then I uninstalled the CANSIM packege from my PC and tried to install it  from Github [ remotes::install_github("mountainmath/cansim") ] and got couple of error massages. So I was unable to install the package from Github. Don't know what to do. Sorry for bugging you so many times. 

Thanks,
Keya

**Comment by mountainMath** [comment]
hm. I just pushed another update to master, but that should not make a difference. Install using
```
remotes::install_github("mountainmath/cansim")
```
works without a problem for me (on MacOS). What error message are you getting?

**Comment by biswask** [comment]
Here is the massage I am getting:

Downloading GitHub repo mountainmath/cansim@master
√  checking for file 'C:\Users\kbiswas\AppData\Local\Temp\1\RtmpS2AusD\remotes2f085c7017d3\mountainMath-cansim-c49d5bd/DESCRIPTION' (647ms)
-  preparing 'cansim':
√  checking DESCRIPTION meta-information ... 
-  excluding invalid files
   Subdirectory 'R' contains invalid file names:
     'Statistics Canada Open Licence Agreement'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'cansim_0.2.3.tar.gz'
   
Installing package into ‘\\nasfil02p.gos.ca/ICTUser$/kbiswas/My Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
'\\nasfil02p.gos.ca\ICTUser$\kbiswas\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'cansim' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : there is no package called 'cansim'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'cansim'
* removing '\\nasfil02p.gos.ca/ICTUser$/kbiswas/My Documents/R/win-library/3.6/cansim'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/kbiswas/AppData/Local/Temp/1/RtmpS2AusD/file2f087355f91/cansim_0.2.3.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

Thanks,
Keya

**Comment by dshkol** [comment]
hi @biswask, when you say you uninstalled the package from your PC, how did you do that?

@mountainMath , just checked install of this latest version and worked fine for me. I suspect there could be an issue depending on how this package was removed.

**Comment by biswask** [comment]
I have uninstalled the package using this code: remove.packages("cansim")
After that I checked in my C drive location where all the packages are installed. there was no folder named "cansim".

Thanks,
Keya.

**Comment by dshkol** [comment]
@mountainMath -I dont have access to a PC right now to verify the installation, only macs. We've had OS related installation issues in the past due to pathing issues, for example.

**Comment by biswask** [comment]
Hi, 
Timeout argument is working now. Thank you so much for all your help!
Keya.
