### ISSUE TITLE
categories as factors

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cansim#62]
`normalize_cansim_values` now has an optional parameter `factors=FALSE`, if set to `TRUE` the categories will all be returned as factors. It might make sense to set the default option to `TRUE`, but that might lead to breaking changes in some cases.

**Comment by mountainMath** [comment]
Going with default=FALSE, setting it to TRUE will break our "Working with Hierarchies" vignette. When subsetting a factor variable without casting to defaults to integer (factor level), instead of character if not explicitly cast to handled as factor. Thinking this will break other people's code too.

**Comment by dshkol** [comment]
Fixed in #64
