### ISSUE TITLE
caching issue with large vector download

### ISSUE THREAD

**Issue by t-hind** [mountainMath/cansim#66]
I was using your package to do a large download of vectors from Stats Can and I ran into a small bug.

When I did 
v <- list(v1,v2,v3,v4,v5,v6,v7)
where each v1/v2 ect...  are a list of 300 characters for different stats can vectors a caching issue would arise. 

After I did

outputList <- lapply(v,get_cansim_vector,start_time ="2000-01-01")

the data saved from each call on v1/v2 ect would always be identical. When I change the order of the vectors in the list "v", the output changed but was still identical across all the pulls. It just happened that whichever of v1/v2 ect was first would be the proper data. 

This just seems to be a caching issue and when I dropped the group size to 150 vectors (down from the maximum of 300), the code worked as expected. If possible I suspect adding a refresh option like in get_cansim would solve this problem. Great package though and thank you so much for making it!

**Comment by mountainMath** [comment]
Hmm. The `get_cansim_vector()` and `get_cansim_vector_for_latest_periods()` don't cache the data locally, only the whole table download `get_cansim()` uses a local cache. I suspect it has to do with the limit StatCan puts on the number of rows it will return on a call. I forgot what the exact number of rows is, it would probably be good to add that to the documentation. Or even better, rerun and paginate if the returned value runs up against the limit.

Can you post the code that produces the error so I can investigate?

**Comment by t-hind** [comment]
Yes no problem,

Here is the code that I ran at 11am EST today

library(cansim) #API Wrapper to Stats Can

# X is an excel file that has 2070 vectors with labels associated with them
x <- read.xlsx("vectors.xlsx")

# I break the large file into batches of 300, the max number of vectors that you can access at a time
v1 <- x$VECTOR[1:300]
v2 <- x$VECTOR[301:600]
v3 <- x$VECTOR[601:900]
v4 <- x$VECTOR[901:1200]
v5 <- x$VECTOR[1201:1500]
v6 <- x$VECTOR[1501:1800]
v7 <- x$VECTOR[1801:nrow(x)]

# Save them as a list
v <- list(v1,v2,v3,v4,v5,v6,v7)

# List apply with get_cansim_vector from 2000-01-01
outputList <- lapply(v, get_cansim_vector,start_time = "2000-01-01")

#Test if the data frames pulled are unique
y <- data.frame(matrix(data = T, ncol = length(outputList), nrow = length(outputList)))
for (i in 1:length(outputList)) {
  y$X1[i] <- identical(outputList[[1]],outputList[[i]])
  y$X2[i] <- identical(outputList[[2]],outputList[[i]])
  y$X3[i] <- identical(outputList[[3]],outputList[[i]])
  y$X4[i] <- identical(outputList[[4]],outputList[[i]])
  y$X5[i] <- identical(outputList[[5]],outputList[[i]])
  y$X6[i] <- identical(outputList[[6]],outputList[[i]])
  y$X7[i] <- identical(outputList[[7]],outputList[[i]])
}

The output of the should be all FALSE (with TRUE where outputList[[i]] is compared to itself). When I ran this today (Aug 9, 2019) the output was:
          X1            X2           X3             X4            X5            X6            X7
1	TRUE	TRUE	TRUE	FALSE	FALSE	FALSE	FALSE
2	TRUE	TRUE	TRUE	FALSE	FALSE	FALSE	FALSE
3	TRUE	TRUE	TRUE	FALSE	FALSE	FALSE	FALSE
4	FALSE	FALSE	FALSE	TRUE	TRUE	TRUE	FALSE
5	FALSE	FALSE	FALSE	TRUE	TRUE	TRUE	FALSE
6	FALSE	FALSE	FALSE	TRUE	TRUE	TRUE	FALSE
7	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	TRUE

So now it looks like the output for 1:3 are the same, 4:6 are the same and 7 is unique. A change from earlier but still duplicate data frames arise when they shouldn't be.

Here is also the code and output testing/showing the v1:v7 are unique

#Test if vectors are unique
z <- data.frame(matrix(data = T, ncol = length(outputList), nrow = length(outputList)))
for (i in 1:length(outputList)) {
  z$X1[i] <- identical(v1,v[[i]])
  z$X2[i] <- identical(v2,v[[i]])
  z$X3[i] <- identical(v3,v[[i]])
  z$X4[i] <- identical(v4,v[[i]])
  z$X5[i] <- identical(v5,v[[i]])
  z$X6[i] <- identical(v6,v[[i]])
  z$X7[i] <- identical(v7,v[[i]])
}
z #output below	
          X1            X2           X3             X4            X5            X6            X7
1	TRUE	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE
2	FALSE	TRUE	FALSE	FALSE	FALSE	FALSE	FALSE
3	FALSE	FALSE	TRUE	FALSE	FALSE	FALSE	FALSE
4	FALSE	FALSE	FALSE	TRUE	FALSE	FALSE	FALSE
5	FALSE	FALSE	FALSE	FALSE	TRUE	FALSE	FALSE
6	FALSE	FALSE	FALSE	FALSE	FALSE	TRUE	FALSE
7	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	TRUE

When I drop the number of vectors called together to 150 then this "duplicating" issue goes away (but the code does take longer to run). Let me know if I can help in anyway

**Comment by mountainMath** [comment]
This should be fixed in the latest version.
