### ISSUE TITLE
Can't download any of the Employment Insurance (EI) data from statistics Canada website

### ISSUE THREAD

**Issue by biswask** [mountainMath/cansim#69]
Hello,

Good morning.

I am trying to download the EI data (14-10-0005-01, 14-10-0011-01 etc) and getting the following error message. Can you please take a look and let me know whether I am doing anything wrong or not. 

Thanks in advance,
Keya.

ei_0022=get_cansim("14-10-0011-01",refresh=TRUE, timeout=10000) # downloading the data

Accessing CANSIM NDM product 14-10-0011 from Statistics Canada
Parsing data
Folding in metadata
Error in seq.default(additional_indices[3] + 1, additional_indices[4] -  : 
  'to' must be a finite number

**Comment by biswask** [comment]
I tried to download other data tables from Statistics Canada website (i.e 282-0001, 281-0063, 
284-0001) and they are working except all the EI data files.

Any help will be much appreciated.

Thanks again,
Keya

**Comment by mountainMath** [comment]
Thanks for flagging this. It appears to be a problem with unexpected metadata formatting. I have meetings all morning, will check in more detail in the afternoon. Did the EI data work before or is this the first time you tried to access it?

I pushed a quick fix in the `metadata_quickfix` branch, you can install it via
```
remotes::install_github("mountainmath/cansim@metadata_quickfix")
```
This will ignore the metadata if there are problems with it, so you won't have the hierarchy information available for this table when using the quick fix, but the rest works.

**Comment by mountainMath** [comment]
It appears that StatCan changed the way it encodes the metadata sometime between their August 9 release, which still has the old metadata format, and their August 12 release, which has a new metadata format. The current version of the package works fine for any table last updated on or before August 9 and is broken for any table updated on or after August 12.

I am merging the quick-fix into master for now to make it easier to install via just
```
remotes::install_github("mountainmath/cansim")
```

This will simply gracefully fail if there are issues with the metadata and not fold it into the data, so metadata is currently not available for any table released on or after August 12.

Will tend to this later today and figure out a workaround to fix this.

**Comment by mountainMath** [comment]
Newest version in master branch should now restore metadata access for tables released on or after August 12. And it should still work with the old tables too.
