### ISSUE TITLE
Got timeout from StatCan, giving up

### ISSUE THREAD

**Issue by colemanrob** [mountainMath/cansim#77]
I recently upgraded to ubuntu 20.04 and am using R 4.02.  For some reason I get timeout errors in rapid succession when calling a table.

`> births <- get_cansim("17-10-0016", refresh = TRUE, timeout = 1000)

Accessing CANSIM NDM product 17-10-0016 from Statistics Canada
Got timeout from StatCan, trying again
Got timeout from StatCan, trying again
Got timeout from StatCan, trying again
Got timeout from StatCan, giving up
Error: Problem downloading data, multiple timeouts.
Please check your network connection. If your connections is fine then StatCan servers might be down.`

The error messages are immediate as though I was behind a proxy (I'm not, i'm on my home connection).  Interestingly, `cancensus` works fine.  is there a dependency i might be missing?

appreciate any help

**Comment by mountainMath** [comment]
Not sure, I can't reproduce this on my machine. It could be that StatCan servers were having problems at the time you tried, that does happen at times. If you are still having the same problem, can you check what result the following gives you:
```
r<-httr::GET("https://www150.statcan.gc.ca/n1/tbl/csv/17100016-eng.zip")
r$status_code
```

**Comment by colemanrob** [comment]
strange.  i get an error code
`> r<-httr::GET("https://www150.statcan.gc.ca/n1/tbl/csv/17100016-eng.zip")

Error in curl::curl_fetch_memory(url, handle = handle) : 
  error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type

**Comment by mountainMath** [comment]
Hmm. That looks like an SSL handshake problem. What OS and what openssl version are you using?

**Comment by colemanrob** [comment]
ubuntu 20.04, openSSL 1.1.1f (newest version), libcurl4-openssl-dev 7.68.0-1ubuntu2.1 (newest version)

**Comment by colemanrob** [comment]
just a follow-up; i solved by editing my /etc/ssl/openssl.conf file to include

`openssl_conf = default_conf` 

at the top of the file and

```
[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = ssl_default_sect

[ssl_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=1

```
to the end of the file.

apparently openssl has been upgraded and this behaviour is working as intended - see [here](https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1864689)

Hope this helps ubuntu users who use your excellent package :)

Cheers

**Comment by mountainMath** [comment]
Thanks for figuring this out. That's a good stopgap measure, but the core of the problem seems to be StatCan not enabling TLSv1.3. I will let them know of the problem and ask them to upgrade their servers.

**Comment by manolo20** [comment]
Just out of curiosity. @colemanrob Before modifying your openssl.cnf, did you try to curl the information from the terminal?

I had a similar [issue](https://stackoverflow.com/questions/62595675/status-was-ssl-connect-error-when-using-file-downloadhttps-in-ubuntu-20-0) where I was able to curl the CODR data from the terminal, but the ```library(cansim)``` or ```file.download()``` were failing.
