### ISSUE TITLE
Census Profile Issue

### ISSUE THREAD

**Issue by reisner** [mountainMath/cansim#78]
Hi there,

I'm trying to download the census profile (`98-316-X2016001`) but I'm having issues:

```
> cansim::get_cansim("98-316-X2016001")
Accessing CANSIM NDM product 98-31-6X20 from Statistics Canada
Error: Problem downloading data, returned status code 404.
> cansim::get_cansim("98-316")
Error in cansim_old_to_new(t) :
  Unable to match old CANSIM table number 0098316
> cansim::get_cansim("2016001")
Error in cansim_old_to_new(t) :
  Unable to match old CANSIM table number 2016001
```

**Comment by mountainMath** [comment]
The {cansim} package is for the regular (formerly called CANSIM) tables only. Datasets like census profiles are formatted quite differently and are unfortunately out of the scope of the package.

You can still download the Census profile data from the StatCan webpage at https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/details/download-telecharger/comp/page_dl-tc.cfm?Lang=E

However, the [{cancensus} package](https://mountainmath.github.io/cancensus/index.html) might be a good fit for your needs. If you are only looking for a subset of variables on sub-regions of Canada, it will be much more convenient than downloading the entire dataset from StatCan and wrangling it into shape.

**Comment by reisner** [comment]
Great, thanks for that clarification! I'm gonna have to look into that package and how to filter to what I need! :)
