### ISSUE TITLE
Timeout in get_cansim_vector

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cansim#81]
Expose timeout variable to allow shorter timeout. Maybe also set default to be shorter.

Also think about caching the data for the session duration. We do this for other calls, but not for this one.

**Comment by dshkol** [comment]
Caching makes sense here too.

**Comment by dshkol** [comment]
Were you going to add this or do you want me to? You're the caching guy.

**Comment by mountainMath** [comment]
Pushed directly into the https://github.com/mountainMath/cansim/tree/precompile-vignette branch. I am getting CRAN check error related to the precompile vignette feature:
```
The following directory looks like a leftover from 'knitr':
     ‘figure’
   Please remove from your package.
```
Still leaning toward reverting back to the original way of doing things for now and not precompile the vignettes. Still thinking that somehow this gets taken care of automatically either by pkgdown or by some other way as long as we properly label them as vignettes.

**Comment by dshkol** [comment]
I think can just avoid that by adding `figure$` to `.Rbuildignore`

**Comment by mountainMath** [comment]
I added the timeout variable in the https://github.com/mountainMath/cansim/tree/v0.3.6 branch.
