### ISSUE TITLE
Default `view_cansim_webpage` to vector search page

### ISSUE THREAD

**Issue by boshek** [mountainMath/cansim#85]
Would you consider a PR such that a call to `view_cansim_webpage()` would direct the user to this page:

https://www150.statcan.gc.ca/t1/tbl1/en/sbv.action#tables

Existing functionality would be maintained (ie. specifying the vector) but this way it provides an easy path for users to head straight to that site and search for vectors that way?

**Comment by dshkol** [comment]
@mountainMath what do you think?

**Comment by mountainMath** [comment]
I think this is good. So allowing vectors as input as well as table numbers? Would need to have a clear way to distinguish them, so vectors would have to be prefixed by "v" and it won't allow just giving the vector number?

Could also split this into a separate function like we do for retrieving info as a data frame with `get_cansim_table_info` and `get_cansim_vector_info`. But probably better if it's all in the same function, and the name is already generic enough to be used for both. So I say 👍 too.
