### ISSUE TITLE
geographies and profiles API from Statscan

### ISSUE THREAD

**Issue by hswerdfe** [mountainMath/cansim#89]
Would it be in scope of this project to include access to statscan  [geographies](https://www12.statcan.gc.ca/wds-sdw/cr2016geo-eng.cfm) and [Profile ](https://www12.statcan.gc.ca/wds-sdw/cpr2016-eng.cfm) API?

Thanks...

**Comment by mountainMath** [comment]
The [{cancensus} companion package](https://mountainmath.github.io/cancensus/index.html) probably has that covered, although it is missing the economic region geographies and does not tie into the StatCan WDS but the mirrored data at CensusMapper that (in my biased opinion) has much more useful API service.

The two packages are designed to work well together, both come with a `GeoUID` column that can be used to join the data.

**Comment by hswerdfe** [comment]
Thanks @mountainMath I had not explored cancensus or Census Mapper packages yet. it looks like you need an API key to use them, but the api's I pointed to are  open access [example ](https://www12.statcan.gc.ca/rest/census-recensement/CPR2016.json?lang=E&dguid=2016A000212&topic=14&notes10&stat=0).

**Comment by dshkol** [comment]
@hswerdfe the API keys for censusmapper and cancensus are free and freely available and are only there to prevent abuse as the amount and granularity of data accessible through these APIs is much greater than what Statscan has made available up to this point. 

The data is a regularly refreshing mirror of Statscan Census data and geography at every available geographic level, and is made available together with defined vector geographic data.

**Comment by hswerdfe** [comment]
Thanks for the clarification and explanation @dshkol. great work to your whole team on these packages!
