### ISSUE TITLE
Convenience function to compute month/month or year/year (or other appropriate) change

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cansim#9]
In many time series it is interesting to look at month over month or year over year (or quarter over quarter) change. We can automate that and add another `Change` column. This could be done by default or be a separate call.

Maybe the best approach is to start build some use cases and see what approach works best.

**Comment by dshkol** [comment]
Thinking about this a little bit, I'm a bit on the fence on this. 

While it's a common task, if the end user is already accepted the barrier to entry of using R, installing a remote package, and downloading cansim tables, they should be able to make their own time series or trend analysis fairly easily. The important thing is that the data is retrieved in tidy, easy to work with formats that enable end-users to do whatever they want to do from an analysis standpoint. 

That's just my own personal opinion. It's tempting to keep adding functionality and helpful tools to a package but eventually you are adding bloat, potential for more bugs, and increasing abstraction.

**Comment by mountainMath** [comment]
Quite frankly, dealing with dates in R is quite a pain though, the task requires some non-trivial manipulations, e.g. join on itself a version with added month, quarter or year to the Date, renamed VALUE and select of join columns. That's a lot of code, and it's quite messy. Encapsulating this makes things more readable and reduces mistakes.

**Comment by dshkol** [comment]
Fair enough, that's valid in this case but you shouldn't add convenience function for every possible use case IMO. I like the idea that you have with cancensushelpers where that is a separate package.

**Comment by mountainMath** [comment]
Agreed. This is probably best situated in a helper package.
